### ISSUE TITLE
Using an Asterisk in the "CloudWatchAppLogs" parameter errors CWL Log Stream creation

### ISSUE THREAD

**Issue by moskey71** [plus3it/terraform-aws-watchmaker#137]
Output seen in CloudWatch Agent Logs:
 
`2019-07-05T22:05:19Z E! CreateLogStream / CreateLogGroup with log group name /aws/ec2/lx/devxx-bxx stream name install_*_logs_i-xxxxx has errors. Will retry the request: InvalidParameterException: 1 validation error detected: Value 'install_*_logs_i-xxxxx' at 'logStreamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^:*]*`

**Comment by lorengordon** [comment]
What inputs did you use, and what were you expecting should happen? Is there some indication in the AWS docs that the expected usage is supported by the CloudWatch Agent or CloudWatch Logs?

Here is the documented API restriction on the log stream name...
* https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogStream.html#CWL-CreateLogStream-request-logStreamName

**Comment by lorengordon** [comment]
Ok, I think I found the relevant docs:

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection

> file_path – Specifies the path of the log file to upload to CloudWatch Logs. Standard Unix glob matching rules are accepted, with the addition of ** as a super asterisk. For example, specifying /var/log/**.log causes all .log files in the /var/log directory tree to be collected. For more examples, see Glob Library.

Give this branch a try: https://github.com/lorengordon/terraform-aws-watchmaker/tree/cwl-wildcard/modules

**Comment by moskey71** [comment]
Just tested it.  This approach allows the logs to be uploaded to CWL, but changing the asterisk to the percent symbol prevents the log stream from being viewed in the console. The log stream name can be clicked on, but it never loads.

As a workaround, selecting "Search Log Group" from within the Log Group will bring up all streams, which allows for the viewing of the log.

**Comment by lorengordon** [comment]
Ok that's easy, just need to use a character that is url-safe.

**Comment by lorengordon** [comment]
There may be other characters in the path that are not url-safe, so I just switched to encoding the path with `urllib.parse.quote(path)`. Give the branch another try please...

**Comment by moskey71** [comment]
Closer, but no cigar.  The log stream is created, but still can't be viewed.

<img width="326" alt="Screen Shot 2019-07-08 at 2 18 14 PM" src="https://user-images.githubusercontent.com/29447475/60833054-6ba4cf80-a18b-11e9-8f37-589a709c4196.png">

**Comment by lorengordon** [comment]
Alright, we can hack around it then, but fundamentally there is a bug in the console since these are valid characters in the log stream name that the console just can't handle properly. Can you open a support case?

**Comment by moskey71** [comment]
Will do

**Comment by moskey71** [comment]
I tried replacing the '*' with '.' and that works fine, though it's a little ugly in the console

`**.log` becomes `...log`


https://github.com/moskey71/terraform-aws-watchmaker/commit/3cc7bdbc5bc57b744e3018097bce5ff3ee7d715a#diff-89543a5acaa9dcdd3a588914c7d159c6R727

**Comment by lorengordon** [comment]
Yeah, that kind of sucks. Maybe try a few characters that are less common in a directory/file path, and that are not generally special url characters, `!~|`?

**Comment by moskey71** [comment]
Pipe is unsafe and Question Mark is reserved.  
https://perishablepress.com/stop-using-unsafe-characters-in-urls/

I can update the code to use the Exclamation and open a PR, if you agree

**Comment by lorengordon** [comment]
Any of the "safe" special characters that actually work in the console and are not so commonly used in a path would be fine. I'd also avoid `+` since browsers often interpret that as a space... `!'(),`
