### ISSUE TITLE
Seems Like watchmaker-lx-autoscale.template.cfn.json Implements a Bad Assumption

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/terraform-aws-watchmaker#74]
Recently rebased [cfn-gitlab() against the current `watchmaker-lx-autoscale.template.cfn.json` template. Deployed a testing instance with the `ScaleUpSchedule`/`ScaleDownSchedule` defined: was surprised to come in, this morning, to find that, even though the overall deployed stack's `DesiredCapacity` was `1`, I was seeing two instances in the EC2 console. Dug through the code and found:

    "ScaleUpScheduledAction": {
      "Condition": "UseScheduledAction",
      "Properties": {
        "AutoScalingGroupName": { "Ref": "GitLabASG" },
        "DesiredCapacity": { "Ref": "MaxCapacity" },
        "Recurrence": { "Ref": "ScaleUpSchedule" }
      },
      "Type": "AWS::AutoScaling::ScheduledAction"
    }

It _seems_ like it would be better if the `ScaleUpScheduledAction` block's:

        "DesiredCapacity": { "Ref": "MaxCapacity" },

were

        "DesiredCapacity": { "Ref": "DesiredCapacity" },

Granted, as an upstream project, Watchmaker likely makes different assumptions and I'm free to alter things to fit my project's particular needs but felt it was worth a discussion &mdash; thus I'm marking this a question rather than bug.

**Comment by lorengordon** [comment]
It's intentional. Learned the hard way. Rationale described in this PR for the RDSH nodes... https://github.com/plus3it/cfn/pull/170
